-- signature_requests — in-app electronic signature flow for the three NCCP/Equifax
-- compliance documents (Borrower Fact Find, NCCP Needs Analysis, Credit File
-- Authorisation).
--
-- Run this in: Supabase Dashboard → SQL Editor → New query → paste → Run.
-- Safe to re-run (idempotent: IF NOT EXISTS guards).
--
-- One row per (document, signer). A signer is emailed a link containing a RAW
-- one-time token; the DB stores ONLY a SHA-256 hash of that token (token_hash) so
-- a database leak can't be replayed as a signing link. The raw token exists only
-- in the emailed URL. See utils/sign-token.ts.
--
-- The captured signature (base64 PNG), the signer's IP + user-agent, and the
-- consent + signed timestamps are the ETA 1999 evidence bundle. `signed_pdf_path`
-- points at the rendered, server-generated signed PDF in the `signed-documents`
-- Storage bucket (created below).
--
-- The app degrades gracefully if this table is absent (send/list return a
-- "run the migration" message; the signing panel shows empty).

create table if not exists signature_requests (
  id                 uuid primary key default gen_random_uuid(),
  doc_type           text not null check (doc_type in ('fact_find','needs_analysis','credit_authorisation')),
  doc_id             uuid not null,
  signer_index       int  not null default 1,               -- 1 or 2 (two applicants)
  signer_name        text,
  signer_email       text not null,
  token_hash         text not null unique,                  -- SHA-256 hex of the raw token — NEVER the raw token
  status             text not null default 'sent'
                       check (status in ('sent','viewed','signed','declined','expired')),
  created_by         text,                                  -- CF-Access advisor email who sent it
  created_at         timestamptz not null default now(),
  sent_at            timestamptz,
  viewed_at          timestamptz,
  signed_at          timestamptz,
  expires_at         timestamptz,
  signature_image    text,                                  -- base64 PNG data URI of the captured signature
  signer_ip          text,
  signer_user_agent  text,
  consent_at         timestamptz,
  signed_pdf_path    text,                                  -- path in the `signed-documents` bucket
  decline_reason     text
);

create index if not exists signature_requests_doc_idx   on signature_requests (doc_type, doc_id);
create index if not exists signature_requests_token_idx on signature_requests (token_hash);

-- This table holds borrower PII (name, email, IP, a captured signature image) and
-- signing tokens, so the browser anon key must never read it. Server routes use
-- the service key (utils/supabase.ts), which bypasses RLS. Default-deny: do not
-- add a permissive policy here.
alter table signature_requests enable row level security;

-- Private Storage bucket for the rendered signed PDFs. Files are reached only via
-- short-lived signed URLs generated by the server (app code enforces access via
-- the token / CF-Access identity). If your role can't INSERT into storage.buckets
-- from the SQL editor, create the bucket manually in Dashboard → Storage → New
-- bucket → name "signed-documents", Public = OFF.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'signed-documents',
  'signed-documents',
  false,
  20 * 1024 * 1024,          -- 20MB — a signed compliance PDF is a few hundred KB
  array['application/pdf']
)
on conflict (id) do nothing;
