"use client";

import { useState } from "react";
import { jsPDF } from "jspdf";

export default function PropertyGrid({ properties: initialProperties }: { properties: any[] }) {
  const [properties, setProperties] = useState<any[]>(initialProperties);
  const [selectedProperty, setSelectedProperty] = useState<any>(null);
  const [checkedIds, setCheckedIds] = useState<Set<string>>(new Set());
  const [confirmDelete, setConfirmDelete] = useState<{ ids: string[]; label: string } | null>(null);
  const [deleting, setDeleting] = useState(false);

  // --- EMPOWER MATH VARIABLES ---
  const [interestRate, setInterestRate] = useState<number>(6.5);
  const [growthRate, setGrowthRate] = useState<number>(5.0);
  const rentYield = 0.05;

  // --- REAL-TIME CALCULATIONS ---
  let weeklyRent = 0;
  let weeklyCashflow = 0;
  let tenYearValue = 0;
  let tenYearEquity = 0;

  const displayPrice = selectedProperty?.total_package_price || selectedProperty?.house_price;
  if (selectedProperty && displayPrice) {
    const price = displayPrice;
    weeklyRent = (price * rentYield) / 52;
    const annualInterestCost = price * (interestRate / 100);
    const weeklyInterestCost = annualInterestCost / 52;
    weeklyCashflow = weeklyRent - weeklyInterestCost;
    tenYearValue = price * Math.pow((1 + (growthRate / 100)), 10);
    tenYearEquity = tenYearValue - price;
  }

  // --- CHECKBOX HELPERS ---
  const toggleCheck = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setCheckedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    if (checkedIds.size === properties.length) {
      setCheckedIds(new Set());
    } else {
      setCheckedIds(new Set(properties.map(p => p.id)));
    }
  };

  // --- DELETE ---
  const executeDelete = async () => {
    if (!confirmDelete) return;
    setDeleting(true);
    try {
      await fetch("/api/properties/delete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ids: confirmDelete.ids }),
      });
      setProperties(prev => prev.filter(p => !confirmDelete.ids.includes(p.id)));
      setCheckedIds(prev => { const n = new Set(prev); confirmDelete.ids.forEach(id => n.delete(id)); return n; });
      if (selectedProperty && confirmDelete.ids.includes(selectedProperty.id)) setSelectedProperty(null);
    } finally {
      setDeleting(false);
      setConfirmDelete(null);
    }
  };

  // --- PDF ---
  const generatePDF = () => {
    if (!selectedProperty) return;
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185);
    doc.text("Empower Wealth Projection", 20, 30);
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Property: ${selectedProperty.street_address}, ${selectedProperty.suburb}`, 20, 45);
    doc.text(`Purchase Price: $${(selectedProperty.total_package_price || selectedProperty.house_price)?.toLocaleString()}`, 20, 55);
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Interest Rate Assumption: ${interestRate}% (Interest Only)`, 20, 70);
    doc.text(`Capital Growth Assumption: ${growthRate}% per annum`, 20, 78);
    doc.setFontSize(16);
    doc.setTextColor(44, 62, 80);
    doc.text("10-Year Financial Forecast", 20, 95);
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Estimated Weekly Rent: $${Math.round(weeklyRent)}`, 20, 105);
    if (weeklyCashflow >= 0) doc.setTextColor(39, 174, 96);
    else doc.setTextColor(192, 57, 43);
    doc.text(`Weekly Cashflow: ${weeklyCashflow >= 0 ? '+' : ''}$${Math.round(weeklyCashflow)}`, 20, 115);
    doc.setTextColor(142, 68, 173);
    doc.text(`Estimated 10-Year Equity: +$${Math.round(tenYearEquity).toLocaleString()}`, 20, 125);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by PropertyMarketer CRM", 20, 280);
    doc.save(`Wealth_Report_${(selectedProperty.street_address || selectedProperty.suburb || 'Property').replace(/\s+/g, '_')}.pdf`);
  };

  const allChecked = properties.length > 0 && checkedIds.size === properties.length;
  const someChecked = checkedIds.size > 0 && checkedIds.size < properties.length;

  return (
    <>
      {/* Confirm delete dialog */}
      {confirmDelete && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm mx-4 p-6">
            <div className="text-3xl mb-3 text-center">🗑️</div>
            <h3 className="text-base font-bold text-gray-900 text-center mb-1">Delete {confirmDelete.label}?</h3>
            <p className="text-sm text-gray-500 text-center mb-6">This will remove it from the aggregator feed permanently.</p>
            <div className="flex gap-3">
              <button onClick={() => setConfirmDelete(null)}
                className="flex-1 py-2.5 text-sm font-semibold text-gray-600 bg-gray-100 rounded-xl hover:bg-gray-200 transition">
                Cancel
              </button>
              <button onClick={executeDelete} disabled={deleting}
                className="flex-1 py-2.5 text-sm font-semibold text-white bg-red-600 rounded-xl hover:bg-red-700 disabled:opacity-60 transition">
                {deleting ? "Deleting…" : "Delete"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Toolbar */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <label className="flex items-center gap-2 cursor-pointer select-none text-sm text-gray-600">
            <input
              type="checkbox"
              checked={allChecked}
              ref={el => { if (el) el.indeterminate = someChecked; }}
              onChange={toggleAll}
              className="w-4 h-4 rounded border-gray-300 text-blue-600"
            />
            {checkedIds.size > 0 ? `${checkedIds.size} selected` : "Select all"}
          </label>
        </div>
        {checkedIds.size > 0 && (
          <button
            onClick={() => setConfirmDelete({ ids: Array.from(checkedIds), label: `${checkedIds.size} propert${checkedIds.size !== 1 ? "ies" : "y"}` })}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold bg-red-600 text-white rounded-lg hover:bg-red-700 transition"
          >
            🗑️ Delete {checkedIds.size}
          </button>
        )}
      </div>

      {/* Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
        {properties.map((property) => {
          const isChecked = checkedIds.has(property.id);
          return (
            <div key={property.id}
              className={`bg-white rounded-xl shadow-sm border overflow-hidden hover:shadow-md transition flex flex-col ${isChecked ? "border-blue-400 ring-2 ring-blue-200" : "border-gray-200"}`}
            >
              <div className="h-48 bg-gray-100 relative flex items-center justify-center">
                {property.brochure_url ? (
                  <img src={property.brochure_url} className="object-cover w-full h-full" alt="Thumbnail" />
                ) : (
                  <span className="text-gray-400 text-sm font-medium">No Image</span>
                )}
                <span className="absolute top-2 right-2 bg-green-500 text-white px-2 py-1 text-xs font-bold rounded shadow-sm capitalize">
                  {property.status || "available"}
                </span>
                {/* Checkbox top-left */}
                <div className="absolute top-2 left-2" onClick={e => toggleCheck(property.id, e)}>
                  <input
                    type="checkbox"
                    checked={isChecked}
                    onChange={() => {}}
                    className="w-4 h-4 rounded border-gray-300 text-blue-600 cursor-pointer shadow"
                  />
                </div>
              </div>

              <div className="p-5 flex-1 flex flex-col">
                <h3 className="font-bold text-xl text-gray-900">
                  {(property.total_package_price || property.house_price) ? `$${(property.total_package_price || property.house_price).toLocaleString()}` : 'Price TBD'}
                </h3>
                <p className="text-sm text-gray-500 mt-1">
                  {property.street_address || property.suburb || "Unknown"}{property.suburb && property.street_address ? `, ${property.suburb}` : ""} {property.state}
                </p>

                <div className="flex gap-4 mt-4 text-sm text-gray-700 font-medium">
                  <span>🛏️ {property.bedrooms || '-'}</span>
                  <span>🛁 {property.bathrooms || '-'}</span>
                  <span>🚗 {property.car_spaces || '-'}</span>
                </div>

                <div className="mt-auto">
                  <hr className="my-4 border-gray-100" />
                  <div className="flex justify-between items-center gap-2">
                    <span className="text-xs text-gray-400 font-medium uppercase tracking-wider truncate max-w-[100px]">
                      {property.builder_name || "Unknown Builder"}
                    </span>
                    <div className="flex items-center gap-2">
                      <button
                        onClick={() => setConfirmDelete({ ids: [property.id], label: property.street_address || property.suburb || "this property" })}
                        className="p-1.5 rounded-lg text-gray-300 hover:text-red-600 hover:bg-red-50 transition"
                        title="Delete"
                      >
                        🗑️
                      </button>
                      <a
                        href={`/properties/${property.id}`}
                        className="text-gray-500 hover:text-gray-900 text-xs font-semibold underline-offset-2 hover:underline transition"
                      >
                        Detail →
                      </a>
                      <button
                        onClick={() => setSelectedProperty(property)}
                        className="bg-gray-900 hover:bg-gray-800 text-white px-4 py-2 rounded-lg text-sm font-semibold transition shadow-sm"
                      >
                        Open War Room
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* War Room Panel */}
      {selectedProperty && (
        <div className="fixed inset-0 z-50 flex justify-end bg-black bg-opacity-50 transition-opacity">
          <div className="w-full max-w-xl bg-white h-full shadow-2xl flex flex-col">
            <div className="px-6 py-5 border-b border-gray-200 flex justify-between items-center bg-gray-50">
              <div>
                <h2 className="text-xl font-bold text-gray-900">Campaign War Room</h2>
                <p className="text-sm text-gray-500">
                  {selectedProperty.street_address || selectedProperty.suburb}, {selectedProperty.suburb} {selectedProperty.state}
                </p>
              </div>
              <button onClick={() => setSelectedProperty(null)}
                className="text-gray-400 hover:text-gray-700 p-2 rounded-full hover:bg-gray-200 transition">
                ✕ Close
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-6">
              <div className="mb-8 border border-blue-200 bg-blue-50 rounded-xl p-5">
                <h3 className="text-lg font-bold text-blue-900 mb-4 flex items-center">⚡ Empower Intelligence</h3>
                <div className="mb-6 space-y-4">
                  <div>
                    <div className="flex justify-between text-sm font-medium text-gray-700 mb-1">
                      <label>Interest Rate (Interest Only)</label>
                      <span>{interestRate}%</span>
                    </div>
                    <input type="range" min="2" max="10" step="0.1" value={interestRate}
                      onChange={e => setInterestRate(parseFloat(e.target.value))}
                      className="w-full h-2 bg-blue-200 rounded-lg appearance-none cursor-pointer" />
                  </div>
                  <div>
                    <div className="flex justify-between text-sm font-medium text-gray-700 mb-1">
                      <label>10-Year Est. Capital Growth</label>
                      <span>{growthRate}%</span>
                    </div>
                    <input type="range" min="1" max="12" step="0.5" value={growthRate}
                      onChange={e => setGrowthRate(parseFloat(e.target.value))}
                      className="w-full h-2 bg-blue-200 rounded-lg appearance-none cursor-pointer" />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3 mb-4">
                  <div className="bg-white p-3 rounded-lg border border-blue-100 shadow-sm">
                    <p className="text-xs text-gray-500 uppercase font-bold">Purchase Price</p>
                    <p className="text-lg font-bold">${(selectedProperty.total_package_price || selectedProperty.house_price)?.toLocaleString() || 'TBD'}</p>
                  </div>
                  <div className="bg-white p-3 rounded-lg border border-blue-100 shadow-sm">
                    <p className="text-xs text-gray-500 uppercase font-bold">Est. Weekly Rent</p>
                    <p className="text-lg font-bold text-gray-900">${Math.round(weeklyRent)}/wk</p>
                  </div>
                  <div className="bg-white p-3 rounded-lg border border-blue-100 shadow-sm">
                    <p className="text-xs text-gray-500 uppercase font-bold">Weekly Cashflow</p>
                    <p className={`text-lg font-bold ${weeklyCashflow >= 0 ? 'text-green-600' : 'text-red-500'}`}>
                      {weeklyCashflow >= 0 ? '+' : ''}${Math.round(weeklyCashflow)}/wk
                    </p>
                  </div>
                  <div className="bg-white p-3 rounded-lg border border-blue-100 shadow-sm">
                    <p className="text-xs text-gray-500 uppercase font-bold">10-Yr Est. Equity</p>
                    <p className="text-lg font-bold text-purple-600">+${Math.round(tenYearEquity).toLocaleString()}</p>
                  </div>
                </div>
                <button onClick={generatePDF}
                  className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 rounded-lg shadow-sm transition">
                  Generate Branded Wealth Report (PDF)
                </button>
              </div>

              <div>
                <h3 className="text-lg font-bold text-gray-900 mb-4">Marketing Assets</h3>
                <div className="space-y-3">
                  <div className="border border-gray-200 rounded-lg p-4 flex justify-between items-center">
                    <div>
                      <p className="font-bold text-sm">Landing Page</p>
                      <p className="text-xs text-gray-500">Not published yet</p>
                    </div>
                    <button className="bg-gray-100 hover:bg-gray-200 text-gray-800 text-xs font-bold py-2 px-4 rounded">Publish</button>
                  </div>
                  <div className="border border-gray-200 rounded-lg p-4 flex justify-between items-center">
                    <div>
                      <p className="font-bold text-sm">AI Ad Copy</p>
                      <p className="text-xs text-gray-500">Based on builder remarks</p>
                    </div>
                    <button className="bg-gray-100 hover:bg-gray-200 text-gray-800 text-xs font-bold py-2 px-4 rounded">Generate</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
